# <font color='#eb3483'> Numpy Exercises </font>

Numpy is a really handy package to have mastered - these bonus questions are your chance to practice and get the functions engrained. Remember that learning data science is like learning a sport - you'll only get better with time and practice! You can start by importing numpy below:

In [1]:
# your code goes here
import numpy as np

### <font color='#eb3483'>  1. Creating Arrays </font>
For this question we're going to be creating the following array two different ways
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
(a) Start by creating a list with the data and turning it into a numpy array - call it array

In [5]:
# your code goes here
array = np.array([[1, 6, 11], [2, 7, 12], [3, 8, 13], [4, 9, 14], [5, 10, 15]])
print(array)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


(b) **Challenge!** Create the same array, but instead of typing in each value manually into a list generate the matrix using `np.arange`. Hint: Arange creates a vector, you'll need to use reshape and transpose to get the final result

In [25]:
# your code goes here
array_np = np.arange(1, 16,1)

array_np= array_np.reshape(3,5)

array_np = array_np.T

print(array_np)


[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


NameError: name 'shape' is not defined

### <font color='#eb3483'>  2. Array Attributes and Indexing </font>


Now let's delve a little deeper to understand `array`

What's the shape of the array?

In [26]:
# your code goes here
shape = array_np.shape
print(shape)

(5, 3)


What's the type of the array?

In [27]:
# your code goes here

type = array_np.dtype

print(type)

int64


Set the type of array to float (hint: the dtype for float in numpy is np.float64)

In [33]:
# your code goes here
array_np.astype(np.float64)


array([[ 1.,  6., 11.],
       [ 2.,  7., 12.],
       [ 3.,  8., 13.],
       [ 4.,  9., 14.],
       [ 5., 10., 15.]])

Select the 3rd column of the array

In [37]:
# your code goes here
colum_3 = array_np[:, 2]
print(colum_3)


[11 12 13 14 15]


Select the (0,1), (2, 2) and (4,0) elements of the array at the same time

In [43]:
# your code goes here

row = np.array([0, 2, 4])
cols = np.array([1, 2, 0])

points = array_np[row, cols]

print(points)

[ 6 13  5]


Slice into the array to get the top 2x2 square of data (i.e. the first two columns of the first two rows)

In [45]:
# your code goes here

two_two = array_np[:2, :2]

print(two_two)

[[1 6]
 [2 7]]


**Challenge!** Select all values of array that are divisible by 2 (hint you might want to use the `%` (integer division) operator)

In [46]:
# your code goes here
modolu_two = array_np[array_np % 2 == 0]

print(modolu_two)


[ 6  2 12  8  4 14 10]


### <font color='#eb3483'>  3. Growing our array </font>


Now let's start changing our array!

Create a vector with the numbres 16 to 20, call it newCol *(hint: use np.arange)*

In [48]:
# your code goes here

new_Col = np.arange(16, 21, 1)
print(new_Col)

[16 17 18 19 20]


Reverse newCol (i.e. 20 19 18...etc)

In [51]:
# your code goes here

new_Col = new_Col[::-1]
print(new_Col)

[20 19 18 17 16]


Assign the value `100` to the 2nd position in newCol

In [53]:
# your code goes here

new_Col[new_Col == 19] = 100

print(new_Col)


[ 20 100  18  17  16]


Reshape newCol to have dimension (5,1) instead of just (5,)

In [56]:
# your code goes here

reshape = new_Col.reshape((5,1))

print(reshape)

[[ 20]
 [100]
 [ 18]
 [ 17]
 [ 16]]


Add the new column to our array (hint: you should use either vstack or hstack, which one makes sense?)

In [66]:
# your code goes here

hstacked = np.hstack((reshape, reshape))

print(hstacked)




[[ 20  20]
 [100 100]
 [ 18  18]
 [ 17  17]
 [ 16  16]]


### <font color='#eb3483'>  4. Aggregations </font>
Now let's build some aggregations of our array:

Get the average value in our matrix

In [67]:
# your code goes here
print('Average: ', np.mean(reshape))

Average:  34.2


Now get the average for each column

In [73]:
# your code goes here
print('Average (colum) ', hstacked.mean(axis=0))


Average (colum)  [34.2 34.2]


Get the standard deviation of our matrix

In [74]:
# your code goes here
print('Standard Deviation ', np.std(hstacked))


Standard Deviation  32.92658500361068


**Challenge!** Get the maximum value in the array, but only include values that are less than the average value of the matrix

In [78]:
# your code goes here
average = np.mean(hstacked)
print('Average: ', average)

filter = hstacked[hstacked < average]

max= np.max(filter)

print('filtered max: ', max)

Average:  34.2
filtered max:  20
